# WSO2 MI 4.4.0 Configuration for Banking Document System

[server]
hostname = "wso2mi-banking-docs"
offset = 0
enable_mtom = true
enable_swa = true

# HTTP Transport Configuration
[transport.http]
socket_timeout = 180000
core_worker_pool_size = 400
max_worker_pool_size = 500
listener.enable = true
listener.port = 8290

# HTTPS Transport Configuration  
[transport.https]
socket_timeout = 180000
core_worker_pool_size = 400
max_worker_pool_size = 500
listener.enable = true
listener.port = 8253

# Management API Configuration (for health checks)
[management_api]
enable = true
port = 9164

# User Store Configuration
[user_store]
type = "read_only_ldap"

# Primary Keystore Configuration
[keystore.primary]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

# TLS Keystore Configuration (for HTTPS)
[keystore.tls]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

# Truststore Configuration
[truststore]
file_name = "repository/resources/security/client-truststore.jks"
password = "wso2carbon"

# Internal Keystore for encryption
[keystore.internal]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

# Symmetric Key Configuration
[secrets]
alias = "symmetric.key.value"
algorithm = "AES"

# Logging Configuration for better debugging
[logging]
level = "INFO"
enable_structured_logging = false
appenders = "CARBON_CONSOLE, CARBON_LOGFILE"

# Enhanced logging for banking operations
[[logging.loggers]]
name = "org.apache.synapse"
level = "INFO"
additivity = false
appenders = ["CARBON_CONSOLE", "CARBON_LOGFILE"]

[[logging.loggers]]
name = "org.wso2.micro.integrator"
level = "INFO" 
additivity = false
appenders = ["CARBON_CONSOLE", "CARBON_LOGFILE"]

# Banking Document System specific logging
[[logging.loggers]]
name = "com.banking.document"
level = "DEBUG"
additivity = false
appenders = ["CARBON_CONSOLE", "CARBON_LOGFILE"]

# Database Configuration (if needed for banking operations)
# [database.config]
# url = "jdbc:mysql://localhost:3306/banking_docs"
# username = "banking_user"
# password = "banking_pass"
# driver = "com.mysql.cj.jdbc.Driver"

# JMS Configuration (if using message queues)
# [transport.jms]
# listener_enable = true
# sender_enable = true

# Security Configuration
[security]
# Enable security for banking operations
enable_security = true

# CORS Configuration for web clients
[cors]
enabled = true
allowed_origins = ["*"]
allowed_headers = ["Authorization", "Content-Type", "Accept"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_credentials = true

# Performance Tuning for Banking Document System
[performance]
# Connection pool settings
max_connections = 100
connection_timeout = 30000
socket_timeout = 60000

# Cache settings for document retrieval
enable_global_cache = true
cache_timeout = 300000

# Message Size Limits (important for document processing)
[message_size]
# Set higher limits for document attachments (50MB)
max_message_size = 52428800
# Axis2 level message size (50MB)
axis2_max_message_size = 52428800

# Threading Configuration
[threading]
core_pool_size = 20
max_pool_size = 100
keep_alive_time = 60

# System Parameters
[system.parameter]
'javax.net.ssl.trustStore' = "repository/resources/security/client-truststore.jks"
'javax.net.ssl.trustStorePassword' = "wso2carbon"
'java.naming.factory.initial' = "org.wso2.carbon.naming.CarbonJavaContextFactory"

# Health Check Configuration (WSO2 MI 4.4.0 feature)
[health_check]
enable = true
# Health check will be available at http://localhost:8290/healthz

# Metrics and Monitoring
[metrics]
enable = true
jvm_metrics_enable = true

# Container-specific configurations
[container]
# Optimize for containerized deployment
enable_container_logs = true
log_level = "INFO"
