# k8s-manifests/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wso2mi-config
  namespace: banking-document-system
data:
  deployment.toml: |
    [server]
    hostname = "wso2mi-banking-docs"
    hot_deployment = true
    
    [keystore.tls]
    file_name = "wso2carbon.jks"
    password = "wso2carbon"
    alias = "wso2carbon"
    key_password = "wso2carbon"
    
    [truststore]
    file_name = "client-truststore.jks"
    password = "wso2carbon"
    alias = "symmetric.key.value"
    algorithm = "AES"