apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2mi-banking-document-system
  namespace: banking-document-system
spec:
  replicas: 1  # Commencer avec 1 pour éviter surcharge et observer stabilité
  selector:
    matchLabels:
      app: wso2mi-banking-document-system
  template:
    metadata:
      labels:
        app: wso2mi-banking-document-system
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: wso2mi-banking-document-system
          image: medlas/wso2mi-banking-document-system:latest
          ports:
            - containerPort: 8290
            - containerPort: 8253
          env:
            - name: MI_SERVER_HOST
              value: "wso2mi-banking-docs"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /
              port: 8290
            initialDelaySeconds: 360      # attendre ~6 minutes avant de vérifier le "liveness"
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8290
            initialDelaySeconds: 300      # attendre ~5 minutes pour readiness
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - name: config-volume
              mountPath: /home/wso2carbon/wso2mi-4.2.0/conf/deployment.toml
              subPath: deployment.toml
      volumes:
        - name: config-volume
          configMap:
            name: wso2mi-config
