apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2mi-banking-document-system
  namespace: banking-document-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2mi-banking-document-system
  template:
    metadata:
      labels:
        app: wso2mi-banking-document-system
    spec:
      terminationGracePeriodSeconds: 90
      containers:
        - name: wso2mi-banking-document-system
          image: medlas/wso2mi-banking-document-system:latest
          ports:
            - containerPort: 8290
            - containerPort: 8253
          env:
            - name: MI_SERVER_HOST
              value: "wso2mi-banking-docs"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1536m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.awt.headless=true"
          resources:
            requests:
              memory: "768Mi"
              cpu: "300m"
            limits:
              memory: "2048Mi"
              cpu: "1500m"
          livenessProbe:
            httpGet:
              path: /services
              port: 8290
            initialDelaySeconds: 180
            periodSeconds: 45
            timeoutSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /services
              port: 8290
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 5
          volumeMounts:
            - name: config-volume
              mountPath: /home/wso2carbon/wso2mi-4.2.0/conf/deployment.toml
              subPath: deployment.toml
      volumes:
        - name: config-volume
          configMap:
            name: wso2mi-config
